import { ProjectGeneratorAPI } from '@/api/ProjectGenerator'
import path from 'path'
import fs from 'fs-extra'

interface CustomOptions {
  worskpaces: string[]
}

export async function vanillaJsGenerator (api: ProjectGeneratorAPI<CustomOptions>) {
  api.onGenerate(async () => {
    await fs.ensureDir(api.options.projectPath)

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const pkg: any = {
      name: api.options.projectName,
      description: 'My new project',
      version: '0.0.0',
      main: 'index.js',
      private: true,
    }

    if (api.customOptions.worskpaces) {
      pkg.workspaces = api.customOptions.worskpaces
      await fs.writeJson(path.join(api.options.projectPath, 'lerna.json'), {
        npmClient: 'yarn',
        useWorkspaces: true,
        version: '0.0.0',
        packages: api.customOptions.worskpaces,
      })
    }

    await fs.writeJson(path.join(api.options.projectPath, 'package.json'), pkg)

    await fs.writeFile(path.join(api.options.projectPath, '.gitignore'), gitignore)
  })
}

const gitignore = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port
`
