fragment prompt on Prompt {
  id
  type
  visible
  enabled
  name
  message
  group
  description
  link
  choices {
    value
    name
    description
    checked
    disabled
    isDefault
  }
  value
  valueChanged
  error {
    message
    link
  }
  tabId
  skin
}
