[package]
name = "guijs"
version = "0.1.0"
description = "A Tauri App"
authors = [ "guijs" ]
license = "MIT"
repository = "https://github.com/Akryum/guijs"
edition = "2018"

[dependencies]
serde_json = "1.0.91"
serde = "1.0"
serde_derive = "1.0"
tauri = { version = "1.2.4", features = ["notification-all", "process-command-api", "shell-open"] }
reqwest = { version = "0.11", features = [ "blocking", "json" ] }
which = "4.1"
dirs-next = "2.0"
openssl-sys = { version = "*", features = ["vendored"] }

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "z"
